// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Savio.MockServer.Data;

#nullable disable

namespace Savio.MockServer.Migrations
{
    [DbContext(typeof(MockDbContext))]
    [Migration("20251219000000_AddResponseBinaryBlobIdToRequestHistory")]
    partial class AddResponseBinaryBlobIdToRequestHistory
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.11");

            modelBuilder.Entity("Savio.MockServer.Data.Entities.MockBinaryBlobEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<byte[]>("Bytes")
                        .IsRequired()
                        .HasColumnType("BLOB");

                    b.Property<string>("ContentType")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("FileName")
                        .HasMaxLength(260)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt");

                    b.ToTable("MockBinaryBlobs");
                });

            modelBuilder.Entity("Savio.MockServer.Data.Entities.MockEndpointEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CallCount")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("DelayMs")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<string>("HeadersJson")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("LastCalledAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Method")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("TEXT");

                    b.Property<int?>("ResponseBinaryBlobId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ResponseBodyBase64")
                        .HasColumnType("TEXT");

                    b.Property<string>("ResponseBodyContentType")
                        .HasColumnType("TEXT");

                    b.Property<string>("ResponseBodyFileName")
                        .HasColumnType("TEXT");

                    b.Property<string>("ResponseBodyJson")
                        .HasColumnType("TEXT");

                    b.Property<string>("ResponseBodyRaw")
                        .HasColumnType("TEXT");

                    b.Property<string>("ResponseMultipartJson")
                        .HasColumnType("TEXT");

                    b.Property<string>("Route")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<int>("StatusCode")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("IsActive");

                    b.HasIndex("Route", "Method")
                        .IsUnique();

                    b.ToTable("MockEndpoints");
                });

            modelBuilder.Entity("Savio.MockServer.Data.Entities.RequestHistoryEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ClientIp")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<int>("DelayMs")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Method")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("TEXT");

                    b.Property<int>("MockEndpointId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("RequestBody")
                        .HasColumnType("TEXT");

                    b.Property<string>("RequestBodyBase64")
                        .HasColumnType("TEXT");

                    b.Property<string>("RequestBodyContentType")
                        .HasColumnType("TEXT");

                    b.Property<string>("RequestBodyFileName")
                        .HasColumnType("TEXT");

                    b.Property<string>("RequestFormJson")
                        .HasColumnType("TEXT");

                    b.Property<string>("RequestHeadersJson")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("RequestedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("ResponseBody")
                        .HasColumnType("TEXT");

                    b.Property<string>("ResponseBodyBase64")
                        .HasColumnType("TEXT");

                    b.Property<int?>("ResponseBinaryBlobId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ResponseBodyContentType")
                        .HasColumnType("TEXT");

                    b.Property<string>("ResponseBodyFileName")
                        .HasColumnType("TEXT");

                    b.Property<string>("ResponseHeadersJson")
                        .HasColumnType("TEXT");

                    b.Property<int>("ResponseStatusCode")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Route")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("MockEndpointId");

                    b.HasIndex("RequestedAt");

                    b.ToTable("RequestHistory");
                });

            modelBuilder.Entity("Savio.MockServer.Data.Entities.UnmockedRequestEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("FirstSeenAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("HitCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LastClientIp")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("LastSeenAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Method")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("TEXT");

                    b.Property<bool>("MockCreated")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("MockCreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("RequestBody")
                        .HasColumnType("TEXT");

                    b.Property<string>("RequestBodyBase64")
                        .HasColumnType("TEXT");

                    b.Property<string>("RequestBodyContentType")
                        .HasColumnType("TEXT");

                    b.Property<string>("RequestBodyFileName")
                        .HasColumnType("TEXT");

                    b.Property<string>("RequestFormJson")
                        .HasColumnType("TEXT");

                    b.Property<string>("RequestHeadersJson")
                        .HasColumnType("TEXT");

                    b.Property<string>("Route")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("LastSeenAt");

                    b.HasIndex("MockCreated");

                    b.HasIndex("Route", "Method");

                    b.ToTable("UnmockedRequests");
                });

            modelBuilder.Entity("Savio.MockServer.Data.Entities.RequestHistoryEntity", b =>
                {
                    b.HasOne("Savio.MockServer.Data.Entities.MockEndpointEntity", "MockEndpoint")
                        .WithMany("RequestHistory")
                        .HasForeignKey("MockEndpointId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MockEndpoint");
                });

            modelBuilder.Entity("Savio.MockServer.Data.Entities.MockEndpointEntity", b =>
                {
                    b.Navigation("RequestHistory");
                });
#pragma warning restore 612, 618
        }
    }
}
